services:
  server:
    container_name: c_server
    image: ${SERVER_NAME}:${BUILD_TAG}
    restart: always
    ports:
     - ${PORT}:${PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/"]
      interval: 2s
      timeout: 60s
      retries: 20
